/*

?- tell('n2m4_max_poss.pl'), time(( mapz( transitive([a,b,c,d], []), [ ], F:C ), length( F, N ), N>23, length(C, K), K=6, write( n2m4_max_poss( F ) ), writeln('.'), fail; told ) ).
% 47,963,083 inferences, 3.719 CPU in 3.773 seconds (99% CPU, 12897636 Lips)
true.

*/

n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->a>b),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->a>c),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->a>d),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->a>b),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->d>c),([d>b,d>b]->d>b),([d>b,b>d]->d>b),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->c>d),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->c>b),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->b>d),([b>d,b>d]->b>d),([b>c,c>b]->b>c),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->a>d),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->a>c),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
n2m4_max_poss([([d>c,d>c]->d>c),([d>c,c>d]->c>d),([d>b,d>b]->d>b),([d>b,b>d]->b>d),([d>a,d>a]->d>a),([d>a,a>d]->d>a),([c>d,d>c]->d>c),([c>d,c>d]->c>d),([c>b,c>b]->c>b),([c>b,b>c]->b>c),([c>a,c>a]->c>a),([c>a,a>c]->c>a),([b>d,d>b]->d>b),([b>d,b>d]->b>d),([b>c,c>b]->c>b),([b>c,b>c]->b>c),([b>a,b>a]->b>a),([b>a,a>b]->b>a),([a>d,d>a]->d>a),([a>d,a>d]->a>d),([a>c,c>a]->c>a),([a>c,a>c]->a>c),([a>b,b>a]->b>a),([a>b,a>b]->a>b)]).
