/*

?- tell('n3m3_max_poss.pl'), time(( mapz( transitive3([a,b,c], []), [ ], F:C ), length( F, N ), N>23, length(C, K), K=6, write( n3m3_max_poss( F ) ), writeln('.'), fail; told ) ).
% 4,718,240,809 inferences, 342.250 CPU in 348.422 seconds (98% CPU, 13785948 Lips)true.

*/

n3m3_max_poss([([c>b,c>b,c>b]->c>b),([c>b,c>b,b>c]->c>b),([c>b,b>c,c>b]->c>b),([c>b,b>c,b>c]->b>c),([c>a,c>a,c>a]->c>a),([c>a,c>a,a>c]->a>c),([c>a,a>c,c>a]->a>c),([c>a,a>c,a>c]->a>c),([b>c,c>b,c>b]->c>b),([b>c,c>b,b>c]->b>c),([b>c,b>c,c>b]->b>c),([b>c,b>c,b>c]->b>c),([b>a,b>a,b>a]->b>a),([b>a,b>a,a>b]->a>b),([b>a,a>b,b>a]->a>b),([b>a,a>b,a>b]->a>b),([a>c,c>a,c>a]->a>c),([a>c,c>a,a>c]->a>c),([a>c,a>c,c>a]->a>c),([a>c,a>c,a>c]->a>c),([a>b,b>a,b>a]->a>b),([a>b,b>a,a>b]->a>b),([a>b,a>b,b>a]->a>b),([a>b,a>b,a>b]->a>b)]).
n3m3_max_poss([([c>b,c>b,c>b]->c>b),([c>b,c>b,b>c]->c>b),([c>b,b>c,c>b]->c>b),([c>b,b>c,b>c]->c>b),([c>a,c>a,c>a]->c>a),([c>a,c>a,a>c]->c>a),([c>a,a>c,c>a]->c>a),([c>a,a>c,a>c]->a>c),([b>c,c>b,c>b]->c>b),([b>c,c>b,b>c]->c>b),([b>c,b>c,c>b]->c>b),([b>c,b>c,b>c]->b>c),([b>a,b>a,b>a]->b>a),([b>a,b>a,a>b]->a>b),([b>a,a>b,b>a]->a>b),([b>a,a>b,a>b]->a>b),([a>c,c>a,c>a]->c>a),([a>c,c>a,a>c]->a>c),([a>c,a>c,c>a]->a>c),([a>c,a>c,a>c]->a>c),([a>b,b>a,b>a]->a>b),([a>b,b>a,a>b]->a>b),([a>b,a>b,b>a]->a>b),([a>b,a>b,a>b]->a>b)]).
n3m3_max_poss([([c>b,c>b,c>b]->c>b),([c>b,c>b,b>c]->b>c),([c>b,b>c,c>b]->b>c),([c>b,b>c,b>c]->b>c),([c>a,c>a,c>a]->c>a),([c>a,c>a,a>c]->a>c),([c>a,a>c,c>a]->a>c),([c>a,a>c,a>c]->a>c),([b>c,c>b,c>b]->b>c),([b>c,c>b,b>c]->b>c),([b>c,b>c,c>b]->b>c),([b>c,b>c,b>c]->b>c),([b>a,b>a,b>a]->b>a),([b>a,b>a,a>b]->b>a),([b>a,a>b,b>a]->b>a),([b>a,a>b,a>b]->a>b),([a>c,c>a,c>a]->a>c),([a>c,c>a,a>c]->a>c),([a>c,a>c,c>a]->a>c),([a>c,a>c,a>c]->a>c),([a>b,b>a,b>a]->b>a),([a>b,b>a,a>b]->a>b),([a>b,a>b,b>a]->a>b),([a>b,a>b,a>b]->a>b)]).
n3m3_max_poss([([c>b,c>b,c>b]->c>b),([c>b,c>b,b>c]->c>b),([c>b,b>c,c>b]->c>b),([c>b,b>c,b>c]->c>b),([c>a,c>a,c>a]->c>a),([c>a,c>a,a>c]->c>a),([c>a,a>c,c>a]->c>a),([c>a,a>c,a>c]->c>a),([b>c,c>b,c>b]->c>b),([b>c,c>b,b>c]->c>b),([b>c,b>c,c>b]->c>b),([b>c,b>c,b>c]->b>c),([b>a,b>a,b>a]->b>a),([b>a,b>a,a>b]->b>a),([b>a,a>b,b>a]->b>a),([b>a,a>b,a>b]->a>b),([a>c,c>a,c>a]->c>a),([a>c,c>a,a>c]->c>a),([a>c,a>c,c>a]->c>a),([a>c,a>c,a>c]->a>c),([a>b,b>a,b>a]->b>a),([a>b,b>a,a>b]->a>b),([a>b,a>b,b>a]->a>b),([a>b,a>b,a>b]->a>b)]).
n3m3_max_poss([([c>b,c>b,c>b]->c>b),([c>b,c>b,b>c]->b>c),([c>b,b>c,c>b]->b>c),([c>b,b>c,b>c]->b>c),([c>a,c>a,c>a]->c>a),([c>a,c>a,a>c]->c>a),([c>a,a>c,c>a]->c>a),([c>a,a>c,a>c]->a>c),([b>c,c>b,c>b]->b>c),([b>c,c>b,b>c]->b>c),([b>c,b>c,c>b]->b>c),([b>c,b>c,b>c]->b>c),([b>a,b>a,b>a]->b>a),([b>a,b>a,a>b]->b>a),([b>a,a>b,b>a]->b>a),([b>a,a>b,a>b]->b>a),([a>c,c>a,c>a]->c>a),([a>c,c>a,a>c]->a>c),([a>c,a>c,c>a]->a>c),([a>c,a>c,a>c]->a>c),([a>b,b>a,b>a]->b>a),([a>b,b>a,a>b]->b>a),([a>b,a>b,b>a]->b>a),([a>b,a>b,a>b]->a>b)]).
n3m3_max_poss([([c>b,c>b,c>b]->c>b),([c>b,c>b,b>c]->c>b),([c>b,b>c,c>b]->c>b),([c>b,b>c,b>c]->b>c),([c>a,c>a,c>a]->c>a),([c>a,c>a,a>c]->c>a),([c>a,a>c,c>a]->c>a),([c>a,a>c,a>c]->c>a),([b>c,c>b,c>b]->c>b),([b>c,c>b,b>c]->b>c),([b>c,b>c,c>b]->b>c),([b>c,b>c,b>c]->b>c),([b>a,b>a,b>a]->b>a),([b>a,b>a,a>b]->b>a),([b>a,a>b,b>a]->b>a),([b>a,a>b,a>b]->b>a),([a>c,c>a,c>a]->c>a),([a>c,c>a,a>c]->c>a),([a>c,a>c,c>a]->c>a),([a>c,a>c,a>c]->a>c),([a>b,b>a,b>a]->b>a),([a>b,b>a,a>b]->b>a),([a>b,a>b,b>a]->b>a),([a>b,a>b,a>b]->a>b)]).
